config/routes.rb
Pickmeup::Application.routes.draw do
  match '/organizers/:organizer_id/events/new', to: 'events#new'
  resources :organizers do
    member do
      match "import_event_brite" => "organizers#import_event_brite", as: "import_events"
    end

    resources :events
  end
  resources :org_sessions

  get "sessions/create"
  get "sessions/destroy"

  # authentication for event organizer
  get 'org_signup', to: 'organizers#new', as: 'org_signup'
  get 'org_login', to: 'org_sessions#new', as: 'org_login'
  get 'org_logout', to: 'org_sessions#destroy', as: 'org_logout'

  get 'events/genre/:id', to: 'events#genre', as: 'events_genre'

  # this is to show the list of all existing pmus for this user
  get '/pmus', to: 'pmus#index', as: 'pmus'

  #For searching functionality
  post '/events/:id', to: 'events#show'

  #For ticket validation
  post '/events/:id/confirm', to: 'events#confirm'

  #help page
  get '/help', to: 'events#help'

  #pmu introduction
  get '/pmu_intro', to: 'events#pmu_introduction'

  #team introduction
  get '/team_intro', to: 'events#team_introduction'

  resources :events do
    resources :pmus do
      member do
        match "add_user/:user_id" => "pmus#add_user", as: "add_user"
        match "add_requesting_user" => "pmus#add_requesting_user", as: "add_requesting_user"
        match "create_new_cab_trip/:user_id" => "pmus#create_new_cab_trip", :as => 'create_new_cab_trip'
        delete "remove_user/:user_id" => "pmus#remove_user", :as => "remove_user"
        delete "remove_requesting_user/:user_id" => "pmus#remove_requesting_user", as: "remove_requesting_user"
      end
    end
  end

  resources :users

  # managing authentication
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match '/signout', to: 'sessions#destroy', as: 'signout'

  # POST request for pmu confirmation
  match 'pmu/confirmation', as: 'pmu_confirmation', to: 'pmus#confirm'

  #root to: 'sessions#new'
  root to: 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base

  # note: rohan is working on this to add another column (EventBriteId)
  attr_accessible :name, :description, :genre, :file, :address, :organizer_id, :DateTime, :filepicker_url, :eventbrite_id

  attr_accessor :file

  # Validation
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :filepicker_url
  validates_presence_of :genre
  validates_presence_of :file
  validates_presence_of :DateTime

  # Associations
  has_many :tickets, dependent: :destroy
  has_many :pmus, dependent: :destroy
  belongs_to :organizer

  # Geocode to get location
  geocoded_by :address
  after_validation  :geocode, :if => :address_changed?

  # Import csv of ticker numbers
  def import(file)
    spreadsheet = Event.open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
        self.tickets.build(row.to_hash)
     end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
      else  raise UnknownFileType.new(File.extname(file.original_filename), file.original_filename)
    end
  end

  def self.importEventBrite(event_id, genre, description, location, date, photo, organizer_id, name, tickethash)

    organizer = Organizer.find(organizer_id)

    result=  Event.find_all_by_eventbrite_id(event_id)
    if result.count !=0
      return
    end
    event = organizer.events.new eventbrite_id: event_id, genre: genre,
                                  description: description, address: location, DateTime: date, filepicker_url: photo, name: name

    event.file = "no file"

    if event.filepicker_url.nil?
      event.filepicker_url = "http://wildbunchadventures.files.wordpress.com/2011/12/enjoying_party_vector-1920x1200.jpg"
    end
    event.save

    tickethash.each do |ticket|
       number=ticket["ticket"]["id"]
       @ticket=event.tickets.new(number: number)
      @ticket.save
    end
  end


  # Return nice datetime
  def format_datetime
    date_time = Time.parse(self.DateTime)

    return date_time.strftime('%a, %b-%d-%Y at %I:%M %p')
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  include EventsHelper

  before_filter :authorize_organizer, only: [:new, :edit, :update, :create, :destroy]

  class UnknownFileType < StandardError
  end

  # The methods below (help, pmu_introduction, team_introduction) are dummy actions to render the views.
  def help
  end

  def pmu_introduction
  end

  def team_introduction
  end

  #This method is to verify the ticket S/N input by the user.
  def confirm

    confirmed = false
    tickets=Ticket.where(:event_id => params[:id])
    tickets.each do |ticket|
      if (ticket.number==params[:code])

        # There are two cases for ticket S/N confirmation
        # 1) The ticket is confirmed for the first time
        # 2) If the ticket has been confirmed before, only the owner of that ticket can be confirmed again
        if(ticket.owner_id == -1)
          ticket.update_attributes(:owner_id => current_user.id)
          confirmed=true
          break
        elsif ticket.owner_id == current_user.id
          confirmed=true
          break
        else
        end
      end
    end

    respond_to do |format|
      format.json {render :json => {:confirmed => confirmed} }
    end
  end


  def genre
    @events=Event.where(:genre=>params[:id])
    @genres = Genre.all
  end

  #rescue_from UnknownFileType, :with => :unknown_file_type
  def unknown_file_type
    flash[:notice] = "The file path you provided is not correct"
    redirect_to new_organizer_event_path(current_organizer)
  end

  def unknown_data_exception
    flash[:notice] = "The file that you submitted for your tickets was not able to be parsed into tickets"
    redirect_to new_organizer_event_path(current_organizer)
  end

  # List all the events
  def index
    if params[:organizer_id] # show organizer's events
      @events=current_organizer.events.all
    else
      @events = Event.all # show all events
    end

    end

  # Create event
  def new
    @event = current_organizer.events.new
  end

  # Edit events
  def edit
    @event = current_organizer.events.find(params[:id])
  end

  # update the event. right now only allow the event organizer to update
  # name, description, genre & address of the event
  def update
    @event = current_organizer.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(:name => params[:event][:name], :description => params[:event][:description],
                                  :genre => params[:event][:genre], :address => params[:event][:address], :DateTime => params[:event][:DateTime],
                                  :file => "not actual file path")

        format.html { redirect_to organizer_events_path(current_organizer)}
      else
        format.html { render action: "edit" }
      end
    end
  end

  # Show an event
  # TODO: for vu: comment, reduce logic
  def show
    @event=Event.find(params[:id])
    @attendee = current_user
    @original_organizer = @event.organizer
    if current_user && ((@pmu = current_user.get_my_pmu(@event.id)))
      # get all potential pmus with keyword search
      @pmu = current_user.get_my_pmu(@event.id)
      @potential_pmus = @pmu.search(params[:search])

      # remember the state of the previously selected filters
      def remember_state(param_name, param)
        if !param.blank?
          session[param_name] = param
        else
          session[param_name] = nil
        end
      end
      [:friends, :location, :time].each do |param_name|
        remember_state(param_name, params[param_name])
      end
      # apply the filters
      if any_non_empty?([params[:friends], params[:location], params[:time]])
        @potential_pmus = @pmu.apply_filters(params[:friends], params[:location],
          params[:time], @potential_pmus)
      end
      @potential_pmus = @potential_pmus.paginate :page=>params[:page], :per_page => 10
    end
  end

  # Create an event
  def create
    organizer = current_organizer
    @event = organizer.events.new(params[:event])
    begin
      @event.import(@event.file)
    rescue UnknownFileType
      unknown_file_type
      return
    rescue  Exception
      unknown_data_exception
      return
    else
    respond_to do |format|
      if @event.save
        format.html { redirect_to organizer_events_path(organizer),
          notice: 'Event was successfully created.' }
      else

        format.html { render action: "new", notice:"event failure #{@event.errors}" }
      end
    end
   end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to organizer_events_url(current_organizer) }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def display_text(pmu)
    if pmu.is_driving?
      return "<strong>" + pmu.owner.name + "</strong>" + " is driving. "
    elsif pmu.is_cab_sharing?
      return pmu.owner.name + " is organizing a cab sharing. "
    elsif pmu.car_sharing == true and pmu.cab_sharing == true
      return pmu.owner.name + " is looking for a car sharing trip or a cab sharing trip. "
    elsif pmu.car_sharing == true
      return pmu.owner.name + " is looking for a car sharing trip. "
    elsif pmu.cab_sharing == true
      return pmu.owner.name + " is looking for a cab sharing trip. "
    else
      return pmu.owner.name + " is not looking for any arrangement. "
    end
  end

  # helper method used in events/show_user_committed.html to format text for car driver
  def format_text_driving_owner(user)
    return user.name + " is driving."
  end

  # helper method used in events/show_user_committed.html to format text for car rider
  def format_text_driving_participant(user)
    return user.name + " is riding."
  end

  # helper method used in the events/show_user_committed.html to format text for cab organizer
  def format_text_cab_organizer(user)
    return user.name + " is organizing the cab trip."
  end

  # helper method used in the events/show_user_committed.html to format text for cab participants
  def format_text_cab_participant(user)
    return user.name + " is participating in the cab trip."
  end

  # helper method used in the events/show_user_uncommitted to format text for cab proposer
  def format_text_cab_proposer(user)
    return user.name + " wants to propose a new cab trip."
  end

  def format_confirmation_status(user, pmu)
    if user.get_confirmation_status(pmu)
      return "Confirmed"
    else
      return "Not Confirmed"
    end
  end
end

app/views/events/_pmus.html.erb
  <% for i in 0..(@potential_pmus.length-1) %>
      <% pmu=@potential_pmus[i] %>
      <div class="container">
        <div id='<%="pmu_modal_"+i.to_s%>' class="modal hide fade in" style="display: none; ">
          <div class="modal-header">
            <a class="close" data-dismiss="modal">×</a>
            <h3><%= pmu.owner.name+" 's Request"%></h3>
          </div>
          <div class="modal-body">

            <% if pmu.is_driving? %>
                <div class="label label-blue2">Car Driving</div>
            <% else %>
                <% if pmu.car_sharing %>
                    <div class="label label-orange">Car Sharing</div>
                <% end %>

                <% if pmu.cab_sharing %>
                    <div class="label label-green">Cab Sharing</div>
                <% end %>
            <% end %><br>
            <ul>
              <i class="icon-calendar"></i>&nbsp;&nbsp; <strong><%= pmu.datetime%></strong><br>
              <i class="icon-user"></i>&nbsp;&nbsp; <strong><%=pmu.max_people %></strong><br>
              <i class="icon-map-marker"></i>&nbsp;&nbsp;<strong> <%= pmu.location %></strong>
            </ul>
            <br>
            <a href='<%= get_google_map_link(pmu.latitude, pmu.longitude) %>' target="_blank" title="Click to see the enlarged version">
              <%= image_tag get_google_map_image_link(pmu.latitude, pmu.longitude) %>
            </a>
            <br>
          </div>
          <div class="modal-footer">
            <div class="btn-right">
              <!-- Only uncommitted users can join the requests. Drivers,the owner of the pmu, and already-joined members cannot join the PMU-->
              <!-- TODO: Why doesn't this work? Work on it later-->
              <% if(!current_user.own_pmu?(pmu)) %>
                  <% if (!pmu.requesting_users.include?(current_user))&&(!pmu.user_pmus.include?(current_user)) %>
                      <a href='<%= add_requesting_user_event_pmu_path(:event_id=>pmu.event.id, :id=>pmu.id) %>' class="btn btn-primary">Request to Join</a>
                  <% end %>
              <% end %>
              <a href='<%= event_path(:id=>pmu.event.id) %>' class="btn btn-success">Back</a>
            </div>
          </div>
        </div>
      </div>



      <% if current_user.has_requested_pmu?(pmu) %>
          <ul>
            <div class="list">
              <i class="icon-user"></i>&nbsp;&nbsp;<span class="label label-warning">Requested</span>
              <%= display_text(pmu).html_safe %><br>
              <a href="#" class="btn btn-warning btn-right">Cancel</a>
              <a onclick="pmuToggle(<%= i %>)"
                 class="btn btn-info btn-right" target="_blank">Details</a>
            </div>
          </ul>
      <% elsif @pmu.requesting_users.include?(pmu.owner) %>


      <% else %>
          <ul>
            <div class="list">
              <i class="icon-user"></i>&nbsp;&nbsp;<%= display_text(pmu).html_safe %><br>
              <ul>
                <i class="icon-map-marker"></i>&nbsp;&nbsp;&nbsp;<%= pmu.location + " (" %><span class="Italics"><%= pmu.distance_from(@pmu).round(1).to_s + " miles)" %></span><br>
                <i class="icon-calendar"></i>&nbsp;&nbsp;<%= pmu.datetime %>
                <a onclick="pmuToggle(<%= i %>)"
                   class="btn btn-info btn-right" target="_blank">Details</a>
              </ul>
            </div>
          </ul>
      <% end %>
  <% end %>

  <p><%= will_paginate @potential_pmus %></p>

app/views/events/edit.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav" %>

    </div>
    <div class='span6'>
      <%= render 'shared/form' %>
    </div>
  </div>
</div>

app/views/events/genre.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav" %>
    </div>
    <div class='span10'>
      <ul class="thumbnails">
        <% for i in 0..(@events.length-1)%>
            <% event=@events[i] %>
            <% if (i%4==0) %>
                <div class="row-fluid">
            <% end %>
            <div class="span3">
              <div class="thumbnail">
                <h4><%= event.name %></h4>
                  <div class="photo_container">
                    <a href=<%="/events/"+event.id.to_s%>>
                      <%= parse_image_tag event.filepicker_url %>
                    </a>
                  </div>
                  <div class="event_location"><%= event.address %></div>
                  <div class="event_location"><%= event.DateTime %></div>
                </div>

              </div>
            <% if (i%4==3) || (i==@events.length-1) %>
                </div>
            <% end %>
        <% end %>
      </ul>


    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav" %>

    </div>
    <div class='span10'>
      <% if current_organizer && !(current_organizer.eventbrite_id.nil?) %>
          <div class='row-fluid'>
            <div class='span2 well'>
                <div class="event_brite"></div>
                <a href='<%= import_events_organizer_path(current_organizer.id) %>' class="btn btn-info btn-right"><i class="icon-share"></i>&nbsp;Import</a>
            </div>
          </div>
      <% end %>
      <ul class="thumbnails">
          <% for i in 0..(@events.length-1)%>
              <% event=@events[i] %>
              <% if (i%4==0) %>
                <div class="row-fluid">
              <% end %>
              <div class="span3">
                  <div class="thumbnail">
                    <strong><div class="title"><%= event.name %></div></strong>
                        <div class="photo_container">
                          <a href='<%="/events/"+event.id.to_s%>' title="<%= "Click to see #{event.name}'s details" %>">
                            <%= parse_image_tag event.filepicker_url %>
                          </a>
                        </div>
                        <br>
                        &nbsp;<i class="icon-map-marker icon-large"></i>&nbsp;&nbsp;&nbsp;&nbsp;<span class="event_location"><%= " "+event.address %></span><br>
                        &nbsp;<i class="icon-calendar icon-large"></i>&nbsp;&nbsp;<span class="event_location"><%= " "+event.format_datetime %></span>
                    </div>
              </div>
              <% if (i%4==3) || (i==@events.length-1) %>
                </div>
              <% end %>
          <% end %>
      </ul>


      </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav" %>

    </div>
    <div class='span6 well'>
      <%= render 'shared/form' %>
    </div>
  </div>
</div>

app/views/events/pmu_introduction.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/about_nav" %>
    </div>
    <div class="span1"></div>
    <div class='span8 well'>

      <h1><div class="page-header">What is Pick Me Up?</div></h1>
      <br>

      <div class="presentation_container"><div class="presentation"></div></div>
      <br>
      <div class="margin-left">
          <p class="tab content">
            PickMeUp is a service that helps medium and large event organizers to reduce traffic
            congestion by offering alternative transportation modes for their attendants. This web service differs from existing car or cab
            sharing services by only focusing on events and increasing trustworthiness by several filters, thus
            presenting an immediate, compelling reason for the event attendees to use the service.
          </p>
      </div>


    </div>
    <div class="span1"></div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav" %>
    </div>
    <div class='span5 well'>
      <%= render "shared/event" %>

        <!-- Only the creator of the event should be able to modify the events-->
        <% if @original_organizer == current_organizer %>
          <%= link_to @event , :method => :delete, data: { confirm: 'Are you sure?' },
                      :class => "btn btn-warning btn-right" do %>
            <i class="icon-trash"></i>&nbsp; Delete
          <% end %>

          <%=  link_to edit_organizer_event_path(@event), :class=>"btn btn-info btn-right" do %>
            <i class="icon-edit"></i>&nbsp; Edit
          <% end %>
        <% end %>

        <br>
        <% if current_user && (!(current_user.has_existing_pmu?(@event.id)))%>
          <a id="validation" class="btn btn-success btn-right"><i class="icon-ok icon-large"></i>&nbsp;&nbsp;Confirm & Create Request</a>
        <% end %>
      <br>
    </div>

    <% if current_user %>
        <% if current_user.has_existing_pmu?(@event.id) %>
            <div class='span5 well'>
                <div class="page-header"><h3>Request Information</h3></div>
                  <% if current_user.has_own_pmu?(@event.id) %>
                      <% if @pmu.is_uncommitted? %>
                          <%= render :template => 'events/show_user_uncommitted' %>
                      <% else %>
                           <%= render :template => 'events/show_user_driving' %>
                      <% end %>
                  <% else %>
                      <%= render :template => 'events/show_user_committed' %>
                  <% end %>
            </div>
        <% end %>
    <% end %>

  </div>
</div>

<!-- Validation Modal-->
<div class="container">
  <div id="validation_modal" class="modal hide fade in" style="display: none; ">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <span class="font_walkway"><h3>Ticket Validation</h3></span>
    </div>
    <form id="validation_form">
        <div class="modal-body">
          <p>
            <strong>Please type in your ticket Serial Number</strong><br>
            This is to actually verify that you are attending the event
          </p>
          <label for="validation_code"><strong>Validation Code</strong></label>
          <input id="validation_code" type="text" name="validation_code" size="15" />
          <span id="info_validation" class="hideInfo"></span>

          <input type="hidden" name="event" id="event" value="<%= @event.id %>" />
        </div>
        <div class="modal-footer">
          <input id="validation_button" class="btn btn-info" type="submit" value="Confirm"/>
        </div>
    </form>
  </div>
</div>

app/views/events/show.js.erb
$('#pmu_list').html('<%= escape_javascript(render("pmus")) %>');

app/views/events/show_user_committed.html.erb
<% if @pmu.car_sharing %>
    <div class="label label-orange">Car Sharing</div>
<% elsif @pmu.cab_sharing %>
    <div class="label label-green">Cab Sharing</div>
<% end %>

<h4>Congratulations! Your request has been accepted</h4>

<%= render "shared/pmu_confirmation" %>

<%= link_to "Cancel",
            remove_user_event_pmu_path(:event_id => @event.id, :id => @pmu.id, :user_id => current_user.id),
            :method => :delete, :class => "btn btn-warning btn-right" %>

<%= link_to "More Info",
            event_pmu_path(:event_id => @event.id, :id => @pmu.id), :class => "btn btn-info btn-right" %>

app/views/events/show_user_driving.html.erb
<div class="header">You have requested for </div>
<%= render 'shared/pmuLabel' %>
<br>

<div class="header"><i class="icon-book"></i>&nbsp;&nbsp;&nbsp;<strong>Your Trip</strong></div>
    <ul>
      <div class="header"><i class="icon-calendar"></i>&nbsp;&nbsp;<%= @pmu.format_datetime %></div>
      <div class="header"><i class="icon-map-marker"></i> &nbsp;&nbsp;<%= @pmu.location %></div>
    </ul>
<br>

<%= render "shared/pmu_confirmation" %>

<br>

<div class="header"><i class="icon-group"></i>&nbsp;&nbsp;&nbsp;<strong>Participants</strong></div>
<div class="header">
  <ul>
    Current  <a id="driving_modal_toggle" class="btn btn-info"><%= @pmu.users.length.to_s + " / " + @pmu.max_people.to_s + " people" %></a>

    Requested  <a id="driving_request_join_modal_toggle" class="btn btn-info"><%= @pmu.requesting_users.length.to_s + " people" %></a>
  </ul>
</div>

        <div class="container">
          <div id='<%="driving_modal"%>' class="modal hide fade in" style="display: none; ">
            <div class="modal-header">
              <a class="close" data-dismiss="modal">×</a>
              <h3> Current Participants</h3>
            </div>
            <div class="modal-body">
              <ul>
                  <% @pmu.users.each do |user| %>
                      <% if (user.own_pmu?(@pmu)) && (@pmu.is_driving?)%>
                              <li><span class="content"><%= @pmu.owner.name + " (driver)" %></span></li>
                      <% else %>
                      <li>
                        <span class="content"><%= user.name %></span>

                        <% if (current_user.own_pmu?(@pmu)) && (!user.own_pmu?(@pmu)) %>
                            <%= link_to "Remove",
                                        remove_user_event_pmu_path(:event_id => @pmu.event.id, :id => @pmu.id, :user_id => user.id),
                                        :method => :delete, data: { confirm: "Are you sure?"},:class => "btn btn-primary btn-right" %></li>
                        <% end %>
                      <% end %>
                  <% end %>
              </ul>
            </div>
          </div>
        </div>


  <div class="container">
    <div id="driving_request_join_modal" class="modal hide fade in" style="display: none; ">
      <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3> Requested Participants</h3>
      </div>
      <div class="modal-body">
        <% @pmu.requesting_users.each do |user| %>
            <li>
              <span class="content"><%= user.name %></span>
              <%= link_to remove_requesting_user_event_pmu_path(:event_id => @event.id, :id => @pmu.id, :user_id => user.id),
                          :method => :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning btn-right" do %>
                <i class="icon-remove"></i> Remove
              <% end %>

              <%= link_to "Accept",
                               add_user_event_pmu_path(:event_id => @event.id, :id => @pmu.id, :user_id => user.id),
                               :class => "btn btn-info btn-right" %>
              <%= link_to "Details",
                          event_pmu_path(:event_id => @event.id, :id => user.myPmus.where(:event_id => @event.id).first), :class =>"btn btn-primary btn-right"
              %>
            </li>
        <% end %>

      </div>
    </div>
  </div>
<br>

<%= link_to event_pmu_path(:event_id => @pmu.event.id, :id => @pmu.id), :method => :delete,
            data: { confirm: 'Are you sure?' }, :class => "btn btn-warning btn-right" do %>
    <i class="icon-remove"></i> Cancel
<% end %>

<%= link_to "Details", event_pmu_path(:event_id => @pmu.event.id, :id => @pmu.id), :class => "btn btn-primary btn-right" %>

app/views/events/show_user_uncommitted.html.erb
<div class="header">You have requested for </div>

<%= render 'shared/pmuLabel' %>
<a href='<%= event_pmu_path(:event_id => @pmu.event.id, :id => @pmu.id) %>' class="btn btn-info btn-right"><i class="icon-briefcase"></i>&nbsp;Details</a>

<br><br>

<% if @pmu.requesting_users.size > 0 %>
    <div class="header">Cab Sharing Requests</div>
    <ul>
    <% @pmu.requesting_users.each do |user| %>
       <li class="list">
        <%= format_text_cab_proposer(user) %>
         <%= link_to "Decline",
                           remove_requesting_user_event_pmu_path(:event_id => @pmu.event.id, :id => @pmu.id,:user_id => user.id), :method => :delete, :class => "btn btn-warning btn-right" %>
         <%= link_to "Accept",
                     create_new_cab_trip_event_pmu_path(:event_id => @pmu.event_id, :id => @pmu.id, :user_id => user.id), :class => "btn btn-info btn-right" %>
       </li>
      <% end %>
    </ul>
<% end %>

 <br>

    <!-- TODO: Can you asscess session variable from the view ?? -->
  <div class="header"><i class="icon-tags"></i>&nbsp;&nbsp;&nbsp;Find your partners!</div>
  <%= form_tag event_path(@event), id:"name_search" do %>
    <ul>
      <%= text_field_tag :search, params[:search], id:'search_box', placeholder: 'Enter Name' %>
      <%= button_tag(name: 'nil', type: 'submit', class: 'btn btn-primary') do %>
        <i class="icon-search"></i>&nbsp;   Search
      <% end %>
    </ul>
    <br>
    <ul>
        <span class="content"><strong>Filter by</strong></span>
        <ul>
            <div class="content-align2">
                <span class="content"><i class="icon-facebook-sign"></i>&nbsp;&nbsp;friends</span>
                <%= check_box_tag "friends", 'friends', session[:friends] == 'friends', id: 'friends' %>
            </div>
            <div class="content-align">
              <span class="content">Distance&nbsp;<%= select_tag 'location',
               options_for_select(%w{5 10 15 20}, session[:location].to_i) , prompt: "~miles" %></span>
            </div>
            <div class="content-align">
              <span class="content">Time&nbsp;<%= select_tag 'time', options_for_select(%w{0.5 1 2 5},
                session[:time].to_i), prompt: "~hours" %></span>
            </div>
        </ul>
    </ul>
  <% end %>
 <br>
<div class="header"><i class="icon-sitemap"></i>&nbsp;&nbsp;&nbsp;Here are some suggestions!</div>

<div id="pmu_list"><%= render partial: "pmus"  %></div>

app/views/events/team_introduction.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/about_nav" %>
    </div>
    <div class="span1"></div>
    <div class='span8 well'>

        <h1><div class="page-header">About the Team</div></h1>
        <br>
        <div class="team_container">
          <div class="team"></div>
        </div>
      <br>
      <span class="header font_ubuntu tab">We are Team VRAM</span>
      <div class="margin-left">
      <p class="tab">
            <ul class="font_walkway content">
              <li>Andrew Song (Class of 2015, course 6)</li>
              <li>Vu Le (Class of 2014, Williams College)</li>
              <li>Rohan Mahajan (Class of 2015, course 6)</li>
              <li>Minh Tue (Class of 2014, course 6)</li>
            </ul>
        </p>
      </div>
      <br>
    </div>

    <div class="span1"></div>
  </div>
</div>