config/routes.rb
Pickmeup::Application.routes.draw do
  match '/organizers/:organizer_id/events/new', to: 'events#new'
  resources :organizers do
    member do
      match "import_event_brite" => "organizers#import_event_brite", as: "import_events"
    end

    resources :events
  end
  resources :org_sessions

  get "sessions/create"
  get "sessions/destroy"

  # authentication for event organizer
  get 'org_signup', to: 'organizers#new', as: 'org_signup'
  get 'org_login', to: 'org_sessions#new', as: 'org_login'
  get 'org_logout', to: 'org_sessions#destroy', as: 'org_logout'

  get 'events/genre/:id', to: 'events#genre', as: 'events_genre'

  # this is to show the list of all existing pmus for this user
  get '/pmus', to: 'pmus#index', as: 'pmus'

  #For searching functionality
  post '/events/:id', to: 'events#show'

  #For ticket validation
  post '/events/:id/confirm', to: 'events#confirm'

  #help page
  get '/help', to: 'events#help'

  #pmu introduction
  get '/pmu_intro', to: 'events#pmu_introduction'

  #team introduction
  get '/team_intro', to: 'events#team_introduction'

  resources :events do
    resources :pmus do
      member do
        match "add_user/:user_id" => "pmus#add_user", as: "add_user"
        match "add_requesting_user" => "pmus#add_requesting_user", as: "add_requesting_user"
        match "create_new_cab_trip/:user_id" => "pmus#create_new_cab_trip", :as => 'create_new_cab_trip'
        delete "remove_user/:user_id" => "pmus#remove_user", :as => "remove_user"
        delete "remove_requesting_user/:user_id" => "pmus#remove_requesting_user", as: "remove_requesting_user"
      end
    end
  end

  resources :users

  # managing authentication
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match '/signout', to: 'sessions#destroy', as: 'signout'

  # POST request for pmu confirmation
  match 'pmu/confirmation', as: 'pmu_confirmation', to: 'pmus#confirm'

  #root to: 'sessions#new'
  root to: 'events#index'
end

app/controllers/pmus_controller.rb
class PmusController < ApplicationController
  # this class has all the methods that return JSON data from requesting users

  # TODO: authentication for index +confirm later
  before_filter :authorize_user, only: [:show, :new, :create, :add_requesting_user, :create_new_cab_trip]

  before_filter( only: [:edit, :update, :add_user, :remove_user, :remove_requesting_user, :destroy]) {
      |c| c.authorize_user_pmu Pmu.find(params[:id]) }


  # GET: return the list of all pmus relevant to this pmu
  def index

    # This is the pmu that has been joined
    @joined_pmus=Array.new
    requests=current_user.user_pmus #UserPmu.where(:user_id=> current_user.id)
    requests.each do |request|
      pmu=Pmu.find(request.pmu_id)
      if(pmu.pmu_type!="uncommitted")
        @joined_pmus.push(pmu)
      end

    end

    # This is the pmu that has been requested
    @requested_pmus=Array.new
    requests=current_user.requesting_user_pmus #RequestingUserPmu.where(:user_id=> current_user.id)
    requests.each do |request|
      pmu=current_user.myPmus.find_by_event_id(Pmu.find(request.pmu_id).event.id)
      @requested_pmus.push(pmu)
    end

    # This is the pmu owned by the user (uncommitted, cab-sharing)
    @uncommitted_pmus=Array.new
    requests=current_user.myPmus.where(:pmu_type => "uncommitted")
    requests.each do |request|
      if !(@requested_pmus.include?(request))
        @uncommitted_pmus.push(request)
      end
    end
  end

  #Shows the PMU of the corresponding ID
  def show
    @pmu=Pmu.find(params[:id])
    @event=Event.find(params[:event_id])
  end

  #Creates new PMU object
  def new
    @event=Event.find(params[:event_id])

    if current_user.has_existing_pmu?(@event.id)
      redirect_to @event
    end
  end

  # create a new pmu with these attributes. the owner of the pmu is the current user.
  def create
    #This variable sums up the choices made by the users on the pmus/new page and assigns variables based on the value
    choice = params[:sharing_type].to_i+(if(!params[:car_share_type]) then 0 else params[:car_share_type].to_i end)

    respond_to do |format|
      if Pmu.create_new_pmu(params[:max_people],params[:event_id], params[:location], current_user.id,
                            params[:datetime], choice)

        format.html { redirect_to event_path(Event.find(params[:event_id]))}
      else
        format.html { redirect_to new_event_pmu_path(:event_id=>params[:event_id]), :notice => "Failed to create the request!" }
      end
    end
  end

  # Edit the existing PMU
  def edit
    @pmu=Pmu.find(params[:id])
    @event=Event.find(params[:event_id])
  end

  # PUT action to update existing pmu
  def update

    location, datetime, max_people = params[:location], params[:datetime], params[:max_people]

    pmu = Pmu.find(params[:id])

    # If people already have joined this trip, the user should not be able to modify his trip details
    if pmu.users.size > 1
      respond_to do |format|
        format.html {redirect_to event_path(Event.find(params[:event_id])), :notice => "There are other people in this trip! You cannot edit your details"}
      end

    # If there are no people in this trip other than himself, go ahead and chage the details
    else
      #This variable sums up the choices made by the users on the pmus/new page and assigns variables based on the value
      choice = params[:sharing_type].to_i+(if(!params[:car_share_type]) then 0 else params[:car_share_type].to_i end)

      pmu.pmu_type="uncommitted"
      pmu.set_Pmu_type(choice)

      respond_to do |format|
        # When the update is valid
        if (a=pmu.update_attributes(:location => location, :datetime => datetime, :max_people => max_people)) &&
            (b=(user_pmu=pmu.user_pmus.where(:user_id => current_user.id).first).update_attributes(:location => pmu.location, :latitude => pmu.latitude, :longitude => pmu.longitude ))

          format.html { redirect_to event_path(Event.find(params[:event_id]))}
          format.json { render :json => { :msg => "success"} and return}
        #When the update is invalid
        else
          format.html { redirect_to event_path(Event.find(params[:event_id])), :notice => "Wrong Information!"}
          format.json { render :json => { :msg => "error" } and return}
        end
      end
    end

  end

  # GET, POST: add the user to this pmu
  # remove the previous pmu for this event for this user and add this user to this pmu
  def add_user
    pmu = Pmu.find(params[:id])

    requesting_user = User.find(params[:user_id])

    if requesting_user.in?(pmu.users)
      flash_msg = "You have already added this user to this trip."
    else
      added = pmu.add_user(requesting_user.id)

      flash_msg = if added then "You have successfully added " + requesting_user.name else
                  "Unknown errors. Please contact admin."  end
    end

    respond_to do |format|
      format.html do
        flash[:notice] = flash_msg

        redirect_to pmu.event
      end
    end
  end

  # GET/POST: add the requesting user to this pmu
  def add_requesting_user
    pmu = Pmu.find(params[:id])

    if current_user.own_pmu?(pmu) || current_user.has_requested_pmu?(pmu)
      redirect_to pmu.event
    else
      added = pmu.add_requesting_user(current_user.id)

      respond_to do |format|
        format.html do
          flash_msg = if added then "You are successfully added to the requesting list of " + pmu.owner.name else
            "Unknown errors. Please contact admin."  end

          flash[:notice] = flash_msg

          redirect_to pmu.event
        end
      end
    end
  end

  # GET/POST: create a new cab trip for this user + another user
  def create_new_cab_trip
    pmu = Pmu.find(params[:id])
    new_cab_trip_created = pmu.create_new_cab_trip(params[:user_id])

    flash_msg = if new_cab_trip_created then "New cab trip created!" else "Unknown error. Please contact admin" end

    respond_to do |format|
      format.html do
        flash[:notice] = flash_msg

        redirect_to pmu.event
      end
    end
  end

  # DELETE: remove the user from this pmu
  def remove_user
    pmu = Pmu.find(params[:id])
    removed = pmu.remove_user(params[:user_id])

    flash_msg = if removed then "User removed from this trip successfully."
                else "User removed unsuccessfully. Contact admin" end

    respond_to do |format|
      format.html do
        flash[:notice] = flash_msg

        redirect_to pmu.event
      end
    end

  end

  # DELETE: remove the requesting user from this pmu
  def remove_requesting_user
    pmu = Pmu.find(params[:id])
    removed = pmu.remove_requesting_user(params[:user_id])

    flash_msg = "User removed unsuccessfully. Unknown errors."

    if removed
      flash_msg = "User removed successfully from requesting list."
    end

    respond_to do |format|
      format.html do
        flash[:notice] = flash_msg

        redirect_to pmu.event
      end
    end
  end

  # DELETE this pmu & clear all the relations
  def destroy
    pmu = Pmu.find(params[:id])

    flash_msg = if pmu.destroy then "Requested cancelled successfully." else "Unknown errors. Please contact admin" end

    respond_to do |format|
      format.html do
        flash[:notice] = flash_msg

        redirect_to pmu.event
      end
    end
  end

  # POST confirm the attendance of the user with the associated confirmation code
  def confirm
      latitude, longitude, datetime, pmu_code=params[:latitude], params[:longitude], params[:datetime], params[:pmu_code]

      user_pmu,valid_loc,valid_time = UserPmu.validate_pmu_code(pmu_code,latitude,longitude,datetime)

      msg = ""

      if user_pmu.nil?
        msg = "Code incorrect. Please retype."
      else
        # If the user is not at the valid location
        if !valid_loc
          msg = "You are far from your expected location! Please move closer to your proposed location"
        # if the user is not within the valid time
        elsif !valid_time
          msg= "It's not your proposed time!"
        # if all the conditions are satisfied
        else
          msg = "Confirmed"
          user_pmu.confirm(latitude, longitude, datetime)
        end
      end

      render :text=> msg
  end
end

app/helpers/pmus_helper.rb
module PmusHelper
end

app/views/pmus/edit.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav"%>
    </div>
    <div class='span5 well'>
      <%=  render "shared/event" %>
    </div>

    <div class='span5 well'>
      <div class="page-header"><h3>Edit Your Requests</h3></div><br>

      <form action="<%= "/events/"+@event.id.to_s+"/pmus/"+ @pmu.id.to_s %>" method="post" accept-charset="UTF-8">

        <input type="hidden" name="authenticity_token" value='"<%=csrf_meta_tag%>"'>
        <input type="hidden" name="_method" value="put" />

        <div class="header"><i class="icon-bookmark"></i>&nbsp;&nbsp;<strong>Your Choice</strong></div>
        <input type="checkbox" id="car_share_toggle" name="sharing_type" value=<%= Pmu::PMU_CarShare%> /> I want to share a car-ride!<br><br>
        <input type="radio" id="drive_radio" name="car_share_type"  disabled value=<%= Pmu::PMU_CarDrive %>/> I want to drive!<br><br>
        <input type="radio" id="ride_radio" name="car_share_type" disabled value=<%= Pmu::PMU_CarRide %>/> I want to request for a ride!<br><br>

        <input type="checkbox" id="cab_share_toggle" name="sharing_type" value=<%= Pmu::PMU_CabShare%> /> I want to share a cab!<br><br>
        <input type="checkbox" id="no_share_toggle" name="sharing_type" value=<%= Pmu::PMU_NotShare%> /> I will think of it later on!<br><br>

        <div class="header"><i class="icon-map-marker"></i>&nbsp;&nbsp;<strong>Location</strong></div>

        <%= render "shared/gmaps_pmu" %>


        <div class="header"><i class="icon-group"></i>&nbsp;&nbsp;<strong>Max People</strong></div>
        <input id="max_people" type="text" name="max_people" size="30" />
        <span id="info_max_people" class="hideInfo"></span>

        <br><br>

        <div class="header"><i class="icon-calendar"></i>&nbsp;&nbsp;<strong>When is your pick up?</strong></div>
        <input class="datetime" type="text" name="datetime" size="30" /><br><br>

        <input class="btn btn-primary btn-right" type="submit" name="commit" value="Submit" />
      </form>



    </div>
  </div>
</div>

app/views/pmus/index.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav"%>
    </div>
    <div class='span10'>

      <div class="page-header"><h3>My Requests</h3></div>

      <ul class="thumbnails">
        <% for i in 0..(@joined_pmus.length-1)%>
            <% event=@joined_pmus[i].event %>
            <% if (i%4==0) %>
                <div class="row-fluid">
            <% end %>
            <div class="span3">
              <div class="thumbnail">
                <div class="title">
                  <%= event.name %>
                    <div class="label label-blue2">Joined</div>
                </div>
                <div class="photo_container">
                  <a href='<%="/events/"+event.id.to_s%>' title="<%= "Click to see #{event.name}'s details" %>">
                    <%= parse_image_tag event.filepicker_url %>
                  </a>
                </div>
                <div class="event_location"><span class="label label-info">Time</span><%= " "+event.format_datetime %></div>
              </div>
            </div>
            <% if (i%4==3) || (i==@joined_pmus.length-1) %>
                </div>
            <% end %>
        <% end %>
      </ul>

      <ul class="thumbnails">
        <% for i in 0..(@requested_pmus.length-1)%>
            <% event=@requested_pmus[i].event %>
            <% if (i%4==0) %>
                <div class="row-fluid">
            <% end %>
            <div class="span3">
              <div class="thumbnail">
                <div class="title">
                  <%= event.name %>
                  <div class="label label-orange-2">Requested</div>
                </div>
                <div class="photo_container">
                  <a href='<%="/events/"+event.id.to_s%>' title="<%= "Click to see #{event.name}'s details" %>">
                    <%= parse_image_tag event.filepicker_url %>
                  </a>
                </div>
                <div class="event_location"><span class="label label-info">Time</span><%= " "+event.format_datetime %></div>
              </div>
            </div>
            <% if (i%4==3) || (i==@requested_pmus.length-1) %>
                </div>
            <% end %>
        <% end %>
      </ul>

      <ul class="thumbnails">
        <% for i in 0..(@uncommitted_pmus.length-1)%>
            <% event=@uncommitted_pmus[i].event %>
            <% if (i%4==0) %>
                <div class="row-fluid">
            <% end %>
            <div class="span3">
              <div class="thumbnail">
                <div class="title">
                  <%= event.name %>
                  <div class="label label-sky-2">Undecided</div>
                </div>
                <div class="photo_container">
                  <a href='<%="/events/"+event.id.to_s%>' title="<%= "Click to see #{event.name}'s details" %>">
                    <%= parse_image_tag event.filepicker_url %>
                  </a>
                </div>
                <div class="event_location"><span class="label label-info">Time</span><%= " "+event.format_datetime %></div>
              </div>
            </div>
            <% if (i%4==3) || (i==@uncommitted_pmus.length-1) %>
                </div>
            <% end %>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/pmus/new.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav"%>
    </div>
    <div class='span5 well'>
      <%=  render "shared/event" %>
    </div>

    <div class='span5 well'>
        <div class="page-header"><h3>Create new Requests!</h3></div><br>

      <form action="<%= "/events/"+@event.id.to_s+"/pmus" %>" method="post" accept-charset="UTF-8">

        <input type="hidden" name="authenticity_token" value='"<%=csrf_meta_tag%>"'>
        <div class="header"><i class="icon-bookmark"></i>&nbsp;&nbsp;<strong>Your Choice</strong></div>
        <input type="checkbox" id="car_share_toggle" name="sharing_type" value=<%= Pmu::PMU_CarShare%> /> I want to share a car-ride!<br><br>
        <input type="radio" id="drive_radio" name="car_share_type"  disabled value=<%= Pmu::PMU_CarDrive %>/> I want to drive!<br><br>
        <input type="radio" id="ride_radio" name="car_share_type" disabled value=<%= Pmu::PMU_CarRide %>/> I want to request for a ride!<br><br>

        <input type="checkbox" id="cab_share_toggle" name="sharing_type" value=<%= Pmu::PMU_CabShare%> /> I want to share a cab!<br><br>
        <input type="checkbox" id="no_share_toggle" name="sharing_type" value=<%= Pmu::PMU_NotShare%> /> I will think of it later on!<br><br>

        <div class="header"><i class="icon-map-marker"></i>&nbsp;&nbsp;<strong>Location</strong></div>

        <%= render "shared/gmaps_pmu" %>

        <div class="header"><i class="icon-group"></i>&nbsp;&nbsp;<strong>Max People</strong></div>
        <input id="max_people" type="text" name="max_people" size="30" />
        <span id="info_max_people" class="hideInfo"></span>

        <br><br>

        <div class="header"><i class="icon-calendar"></i>&nbsp;&nbsp;<strong>When is your pick up?</strong></div>
        <input class="datetime" type="text" name="datetime" size="30" /><br><br>

        <input class="btn btn-primary btn-right" type="submit" name="commit" value="Submit" />
      </form>

    </div>
  </div>
</div>

app/views/pmus/show.html.erb
<div class="container-fluid">
  <div class='row-fluid'>
    <div class='span2 well'>
      <%= render "shared/nav"%>
    </div>

    <div class='span5 well'>
      <%= render "shared/event" %>
    </div>

    <div class='span5 well'>
      <div class='page-header'>
        <h3><%= @pmu.owner.name + "'s Request" %></h3>
      </div>
      <%= render 'shared/pmuLabel' %>
      <h3><%= @pmu.event.name %></h3>


      <% if !@pmu.is_uncommitted? %>
        <div class="header"><i class="icon-group"></i>&nbsp;&nbsp;Current Participants <a id="driving_modal_toggle2" class="btn btn-info"><%= @pmu.users.length.to_s + " / " + @pmu.max_people.to_s + " people" %></a> </div>

              <div class="container">
                <div id='driving_modal2' class="modal hide fade in" style="display: none; ">
                    <div class="modal-header">
                    <a class="close" data-dismiss="modal">×</a>
                    <h3> Current Participants (max: <%= @pmu.max_people %> people)</h3>
                  </div>
                  <div class="modal-body">
                    <ul>
                        <% @pmu.users.each do |user| %>
                            <% if (user.own_pmu?(@pmu)) && (@pmu.is_driving?)%>
                                <li><span class="content"><%= @pmu.owner.name + " (driver)" %></span></li>
                            <% else %>
                            <li>
                              <span class="content"><%= user.name %></span>
                              <% if (current_user.own_pmu?(@pmu)) && (!user.own_pmu?(@pmu)) %>
                                  <%= link_to "Remove",
                                              remove_user_event_pmu_path(:event_id => @pmu.event.id, :id => @pmu.id, :user_id => user.id),
                                              :method => :delete, :class => "btn btn-primary btn-right" %></li>
                              <% end %>
                            <% end %>
                        <% end %>
                    </ul>
                  </div>
                </div>
              </div>
        <% end %>

      <br>

      <!-- Display joined users-->
      <% @pmu.user_pmus.each do |joined_pmu| %>
          <% if joined_pmu.is_confirmed? %>
              <span class="label label-success">Confirmed</span>
          <% else %>
              <span class="label label-important">Not Confirmed</span>
          <% end %>

          <% if (joined_pmu.user_id == @pmu.owner_id) && (@pmu.is_driving?) %>
              <span class="header"><strong><%=@pmu.owner.name%></strong> is driving from</span>
          <% else %>
              <span class="header"><strong><%= User.find(joined_pmu.user_id).name %></strong> is going to be at</span>
          <% end %>


          <br>
          <ul>
            <i class="icon-map-marker"></i>&nbsp;&nbsp;<%= joined_pmu.location %><br>
            <i class="icon-calendar"></i>&nbsp;&nbsp;<%= joined_pmu.datetime %><br>
          </ul>
          <a href='<%= get_google_map_link(joined_pmu.latitude, joined_pmu.longitude) %>' target="_blank" title="Click to see the enlarged version">
            <%= image_tag get_google_map_image_link(joined_pmu.latitude, joined_pmu.longitude) %>
          </a>
          <br><br>
      <% end %>

      <br>
      <div class="button-align">
        <!-- Only uncommitted users can join the requests. Drivers,the owner of the pmu, and already-joined members cannot join the PMU-->
        <% if(!@pmu.is_owner?(current_user)) && (!current_user.is_joined?(@pmu)) && (!current_user.has_requested_pmu?(@pmu))%>
            <% if (current_user.has_own_pmu?(@pmu.event.id)) && (current_user.get_own_pmu(@pmu.event.id).is_uncommitted?) %>
                <a href='<%= add_requesting_user_event_pmu_path(:event_id=>@pmu.event.id, :id=>@pmu.id) %>' class="btn btn-primary">Request to Join</a>
            <% end %>
        <% end %>

      </div>
      <a href='<%= event_path(:id=>@pmu.event.id) %>' class="btn btn-info btn-right">Back</a>
      <a href='<%= edit_event_pmu_path(:event_id => @pmu.event.id, :id => @pmu.id) %>' class="btn btn-primary btn-right">Edit</a>
    </div>
  </div>
</div>