config/routes.rb
Pickmeup::Application.routes.draw do
  match '/organizers/:organizer_id/events/new', to: 'events#new'
  resources :organizers do
    member do
      match "import_event_brite" => "organizers#import_event_brite", as: "import_events"
    end

    resources :events
  end
  resources :org_sessions

  get "sessions/create"
  get "sessions/destroy"

  # authentication for event organizer
  get 'org_signup', to: 'organizers#new', as: 'org_signup'
  get 'org_login', to: 'org_sessions#new', as: 'org_login'
  get 'org_logout', to: 'org_sessions#destroy', as: 'org_logout'

  get 'events/genre/:id', to: 'events#genre', as: 'events_genre'

  # this is to show the list of all existing pmus for this user
  get '/pmus', to: 'pmus#index', as: 'pmus'

  #For searching functionality
  post '/events/:id', to: 'events#show'

  #For ticket validation
  post '/events/:id/confirm', to: 'events#confirm'

  #help page
  get '/help', to: 'events#help'

  #pmu introduction
  get '/pmu_intro', to: 'events#pmu_introduction'

  #team introduction
  get '/team_intro', to: 'events#team_introduction'

  resources :events do
    resources :pmus do
      member do
        match "add_user/:user_id" => "pmus#add_user", as: "add_user"
        match "add_requesting_user" => "pmus#add_requesting_user", as: "add_requesting_user"
        match "create_new_cab_trip/:user_id" => "pmus#create_new_cab_trip", :as => 'create_new_cab_trip'
        delete "remove_user/:user_id" => "pmus#remove_user", :as => "remove_user"
        delete "remove_requesting_user/:user_id" => "pmus#remove_requesting_user", as: "remove_requesting_user"
      end
    end
  end

  resources :users

  # managing authentication
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match '/signout', to: 'sessions#destroy', as: 'signout'

  # POST request for pmu confirmation
  match 'pmu/confirmation', as: 'pmu_confirmation', to: 'pmus#confirm'

  #root to: 'sessions#new'
  root to: 'events#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='pmu'>
<head>
  <title>Pick Me Up!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false" %>

  <!-- This is to render google map from the client side -->
  <%= javascript_tag do %>
      <% if (defined? @event) != nil %>
          var latitude = '<%= @event.latitude %>';
          var longitude = '<%= @event.longitude %>';
      <% else %>
          var latitude = null;
          var longitude = null;
      <% end %>
  <% end %>

  <%= filepicker_js_include_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='navbar navbar-fixed-top'>
  <div class='navbar-inner'>
    <div class='container-fluid'>
        <div class='row-fluid'>

          <ul class="nav">
            <li>
              <a class="brand_img" href="/events">
              </a>
            </li>
            <li><a class="brand active">Pick Me Up</a></li>
            <li><a href="/pmu_intro"><i class="icon-info-sign icon-large"></i>&nbsp;About Pick Me UP</a></li>
            <li><a href="/team_intro">About us</a></li>
            <li><a href="/help"><i class="icon-question-sign"></i>&nbsp;Help</a></li>

          </ul>
          <ul class="nav pull-right">

                <% if !current_user & !current_organizer %>
                    <li><a href="/organizers/new">Organizer Sign-Up</a></li>
                    <li class="dropdown">
                      <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="root_log_in"><i class="icon-signin"></i>Log In <strong class="caret"></strong></a>
                        <ul class="dropdown-menu">
                            <li><a id="organizer_log_in" href="#"><i class="icon-user icon-large"></i>&nbsp;<strong>Organizer</strong></a></li>
                            <li class="divider"></li>
                            <li><a id="log_in" href="/auth/facebook"><i class="icon-facebook-sign icon-large"></i>&nbsp;<strong>Attendee</strong></a></li>
                      </ul>
                    </li>
                <% else %>
                  <% if current_user %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Welcome! <strong><%= current_user.name %></strong> <b class="caret"></b>
                      </a>

                      <ul class="dropdown-menu">
                        <li><a href="/pmus">My Request</a></li>
                      </ul>
                    </li>

                    <li class="divider-vertical"></li>
                    <li><a href="/signout" id="sign_out"><i class="icon-signout icon-large"></i>Log Out</a></li>
                  <% elsif current_organizer %>
                    <li class="dropdown">
                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Welcome! <strong><%= current_organizer.name %></strong> <b class="caret"></b>
                        </a>

                      <ul class="dropdown-menu">
                        <li><a href='<%= "/organizers/"+current_organizer.id.to_s+"/events/new"%>'>New Event</a></li>
                        <li class="divider"></li>
                        <li><a href ="<%= organizer_events_path(current_organizer) %>">My Events</a></li>
                      </ul>

                    </li>
                    <li class="divider-vertical"></li>
                    <li><a href="/org_logout"><i class="icon-signout icon-large"></i>Log Out</a></li>
                  <% end %>
                <% end %>
               </ul>

        </div>
    </div>
  </div>
</div>

<%= render partial: "shared/flash_messages", flash: flash %>

<%= yield %>


<!-- "Organize Log-in" modal-->
<div class="container">
  <div id="organizer_login_modal" class="modal hide fade in" style="display: none; ">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3>Log-in as Organizer</h3>
    </div>

    <form id="login_form" action="<%= org_sessions_path %>" method="post" accept-charset="UTF-8">

      <div class="modal-body">
        <label for="email">Email</label>
        <input id="email" type="text" name="email" size="30" />
        <span id="info_email" class="hideInfo"></span>

        <label for="password">password</label>
        <input id="password" type="password" name="password" size="30" />
        <span id="info_password" class="hideInfo"></span>
      </div>
      <div class="modal-footer">
        <input class="btn btn-primary" id="login_button" type="submit" name="commit" value="Log In" />
        <a href="/organizers/new" class="btn btn-success">Sign Up</a>
      </div>
    </form>

  </div>
</div>

<div class="container">
  <div id="pmu_about_code_modal" class="modal hide fade in" style="display: none; ">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <div class="header">What is <strong>PMU confirmation code</strong>?</div>
    </div>
    <div class="modal-body">
      <p class="tab">
        This is to verify that you are at the pick up location, at the right time!
        Please, use your mobile device to check in with the given confirmation code!
      </p>
    </div>
    <div class="modal-footer">
    </div>
  </div>
</div>

</body>
</html>